#!/usr/bin/env python3
"""
generator.py
Fixed and hardened version:
- Corrected inconsistent variable names (comfy_url vs comfyui_url vs comfyurl)
- Improved payload building and safeguards
- Added clearer logging and safer tmp file cleanup
- Exports a Generator class for Modly
"""

import os
import time
import json
import requests
import shutil
import subprocess
import sys
from pathlib import Path

COMFYUI_URL = os.environ.get("COMFYUI_URL", "http://127.0.0.1:8188")
POLL_INTERVAL = 3
MAX_WAIT_SECONDS = 600


def _upload_file(comfy_url, path, field_name="image"):
    """Upload a file to ComfyUI. Returns server response JSON if available.

    Uses the provided comfy_url; caller may pass COMFYUI_URL.
    """
    print(f"[generator] Uploading {path} to ComfyUI at {comfy_url} ...")
    with open(path, "rb") as f:
        files = {field_name: (os.path.basename(path), f)}
        resp = requests.post(f"{comfy_url.rstrip('/')}/upload/image", files=files)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status": "ok"}


def _send_workflow(comfy_url, workflow_payload):
    print("[generator] Sending workflow payload to ComfyUI queue ...")
    resp = requests.post(f"{comfy_url.rstrip('/')}/queue", json=workflow_payload, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status": "queued"}


def _poll_for_result(comfy_url, queue_info, timeout_seconds=MAX_WAIT_SECONDS):
    start = time.time()
    print("[generator] Polling for completion ...")
    while time.time() - start < timeout_seconds:
        try:
            qid = None
            if isinstance(queue_info, dict):
                qid = queue_info.get("id") or queue_info.get("prompt_id") or queue_info.get("queue_id")
            # If we have a queue/prompt id, try to inspect that entry
            if qid:
                try:
                    resp = requests.get(f"{comfy_url.rstrip('/')}/queue/{qid}", timeout=10)
                    if resp.status_code == 200:
                        rj = resp.json()
                        if rj.get("status") in ("done", "completed", "complete") or rj.get("finished", False):
                            return rj
                except Exception:
                    pass

            # Fallback: inspect history
            try:
                resp = requests.get(f"{comfy_url.rstrip('/')}/history", timeout=10)
                if resp.status_code == 200:
                    hist = resp.json()
                    if isinstance(hist, list) and len(hist) > 0:
                        latest = hist[0]
                        if latest.get("status") in ("done", "completed") or latest.get("outputs"):
                            return latest
            except Exception:
                pass

        except Exception as e:
            print(f"[generator] Poll exception: {e}")
        time.sleep(POLL_INTERVAL)
    print("[generator] Timeout waiting for ComfyUI result.")
    return None


def _save_placeholder_obj(out_path):
    placeholder = """# Placeholder .obj generated by modly-comfyui-extension
o placeholder
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 0.0 1.0 0.0
f 1 2 3
"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(placeholder)


def _download_file(url, dest_path):
    print(f"[generator] Downloading {url} to {dest_path}")
    resp = requests.get(url, stream=True, timeout=60)
    resp.raise_for_status()
    with open(dest_path, "wb") as f:
        shutil.copyfileobj(resp.raw, f)


def _run_blender_import_save(input_mesh_path, output_blend_path):
    """Try to call Blender to import an OBJ/GLTF and save a .blend file.
    Returns True on success, False otherwise.
    """
    blender_exec = shutil.which("blender")
    if not blender_exec:
        print("[generator] Blender executable not found in PATH; skipping .blend export.")
        return False

    # Create a small temporary Blender Python script to import and save the .blend
    script = """
import bpy
import sys
in_path = sys.argv[-2]
out_path = sys.argv[-1]
# Clear default scene
bpy.ops.wm.read_factory_settings(use_empty=True)
# Import by extension
if in_path.lower().endswith('.obj'):
    bpy.ops.import_scene.obj(filepath=in_path)
elif in_path.lower().endswith('.gltf') or in_path.lower().endswith('.glb'):
    bpy.ops.import_scene.gltf(filepath=in_path)
else:
    print('Unsupported mesh format for automatic import in Blender:', in_path)
# Save the .blend
bpy.ops.wm.save_mainfile(filepath=out_path)
print('Saved .blend to', out_path)
"""
    tmp_script = Path(output_blend_path).with_suffix('.blender_import.py')
    tmp_script.write_text(script, encoding='utf-8')

    cmd = [blender_exec, "--background", "--python", str(tmp_script), "--", str(input_mesh_path), str(output_blend_path)]
    print(f"[generator] Running Blender: {' '.join(cmd)}")
    try:
        proc = subprocess.run(cmd, check=True, capture_output=True, text=True, timeout=300)
        print(proc.stdout)
        if proc.stderr:
            print(proc.stderr, file=sys.stderr)
        try:
            tmp_script.unlink()
        except Exception:
            pass
        return True
    except subprocess.CalledProcessError as e:
        print(f"[generator] Blender failed: {e}\nstdout={e.stdout}\nstderr={e.stderr}")
    except Exception as e:
        print(f"[generator] Blender call exception: {e}")
    finally:
        if tmp_script.exists():
            try:
                tmp_script.unlink()
            except Exception:
                pass
    return False


def generate(inputs, output_dir):
    """Entry point called by Modly.

    inputs: dict with keys from manifest (input_image, text_prompt, existing_file, workflow_json optional)
    output_dir: path where to place the resulting mesh file

    Returns a dict mapping manifest output names to filesystem paths.
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    image_path = inputs.get("input_image")
    text_prompt = inputs.get("text_prompt")
    existing_file = inputs.get("existing_file")
    workflow_json_path = inputs.get("workflow_json")

    # Validate inputs
    if existing_file and not os.path.exists(existing_file):
        print(f"[generator] existing_file provided but not found: {existing_file}")
        existing_file = None

    # Upload files if needed
    try:
        if image_path and os.path.exists(image_path):
            _upload_file(COMFYUI_URL, image_path, field_name="image")
        if existing_file and os.path.exists(existing_file):
            # Some ComfyUI setups might provide a file-upload for assets; reuse image endpoint
            _upload_file(COMFYUI_URL, existing_file, field_name="image")
    except Exception as e:
        print(f"[generator] Upload to ComfyUI failed: {e}")

    # Load workflow
    workflow_payload = None
    if workflow_json_path and os.path.exists(workflow_json_path):
        try:
            with open(workflow_json_path, "r", encoding="utf-8") as f:
                workflow_payload = json.load(f)
        except Exception as e:
            print(f"[generator] Failed to load workflow JSON: {e}")
            workflow_payload = None

    if not workflow_payload:
        # Build a generic placeholder payload that includes text_prompt and input filenames.
        # Replace this with your exported ComfyUI API JSON for a real pipeline.
        payload_nodes = {}
        if image_path:
            payload_nodes["1"] = {
                "class_type": "LoadImage",
                "inputs": {"image": os.path.basename(image_path)}
            }
        else:
            payload_nodes["1"] = {"class_type": "EmptyInput"}

        workflow_payload = {
            "type": "workflow",
            "name": "modly_placeholder_workflow",
            "nodes": payload_nodes,
            "outputs": {"mesh": {"node_id": "1", "output": "mesh"}},
            "meta": {"text_prompt": text_prompt, "existing_file": os.path.basename(existing_file) if existing_file else None}
        }
        print("[generator] No workflow file provided; using internal placeholder payload. Replace with exported workflow.json for real results.")

    # Attach text_prompt into the payload if present (some workflows look in meta.prompt or meta.text_prompt)
    if text_prompt:
        workflow_payload.setdefault('meta', {})['text_prompt'] = text_prompt

    # Send the workflow
    try:
        queue_resp = _send_workflow(COMFYUI_URL, workflow_payload)
    except Exception as e:
        print(f"[generator] Failed to send workflow to ComfyUI: {e}")
        queue_resp = {}

    # Poll for result
    result_info = _poll_for_result(COMFYUI_URL, queue_resp)

    mesh_path = os.path.join(output_dir, "generated_model.obj")
    blend_path = os.path.join(output_dir, "generated_model.blend")

    # Attempt to find an output mesh URL/path in result_info
    if result_info:
        # Heuristic checks for common output locations — adapt to your ComfyUI's response structure
        outputs = None
        if isinstance(result_info, dict):
            outputs = result_info.get("outputs") or result_info.get("result") or result_info.get("outputs_list")
        mesh_url = None
        if isinstance(outputs, dict):
            # Search for a URL value in outputs
            for k, v in outputs.items():
                if isinstance(v, str) and v.lower().endswith(('.obj', '.gltf', '.glb')):
                    mesh_url = v
                    break
                if isinstance(v, dict) and 'url' in v and isinstance(v['url'], str) and v['url'].lower().endswith(('.obj', '.gltf', '.glb')):
                    mesh_url = v['url']
                    break
        elif isinstance(outputs, list):
            for item in outputs:
                if isinstance(item, dict):
                    url = item.get('url') or item.get('file') or item.get('path')
                    if isinstance(url, str) and url.lower().endswith(('.obj', '.gltf', '.glb')):
                        mesh_url = url
                        break
        # If we found a URL, try to download
        if mesh_url:
            try:
                _download_file(mesh_url, mesh_path)
            except Exception as e:
                print(f"[generator] Failed to download mesh from {mesh_url}: {e}")
                _save_placeholder_obj(mesh_path)
        else:
            # No downloadable mesh found — write placeholder
            print("[generator] No mesh URL found in ComfyUI result; creating placeholder.")
            _save_placeholder_obj(mesh_path)
    else:
        print("[generator] No result from ComfyUI; writing placeholder mesh.")
        _save_placeholder_obj(mesh_path)

    # If Blender is available, try to import the mesh and export as .blend
    blend_generated = False
    if os.path.exists(mesh_path):
        try:
            blend_generated = _run_blender_import_save(mesh_path, blend_path)
        except Exception as e:
            print(f"[generator] Blender conversion exception: {e}")
            blend_generated = False

    if not blend_generated:
        # If Blender didn't produce a .blend, remove any incomplete file
        if os.path.exists(blend_path):
            try:
                os.remove(blend_path)
            except Exception:
                pass
        blend_path = None

    result = {"output_mesh": mesh_path}
    if blend_path:
        result["output_blend"] = blend_path

    return result


# Provide a thin wrapper class named `Generator` that implements a generate(inputs, output_dir) method.
class Generator:
    def __init__(self):
        pass

    def generate(self, inputs, output_dir):
        return generate(inputs, output_dir)


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=False, help="Path to test input image")
    ap.add_argument("--out", default="out", help="Output directory")
    ap.add_argument("--workflow", default=None, help="Optional workflow JSON path")
    ap.add_argument("--text", default=None, help="Optional text prompt")
    ap.add_argument("--existing", default=None, help="Optional existing 3D file to edit")
    args = ap.parse_args()
    res = generate({"input_image": args.image, "workflow_json": args.workflow, "text_prompt": args.text, "existing_file": args.existing}, args.out)
    print("Result:", res)
