#!/usr/bin/env python3
"""
generator.py
Template for a Modly extension that routes an input image to a local ComfyUI server.
This script is intentionally explicit and beginner-friendly. Edit the WORKFLOW_PAYLOAD
or provide a 'workflow_json' input that you've exported from ComfyUI (API format).

Modly will call:
    generate(inputs: dict, output_dir: str) -> dict

Return dict maps output names from manifest.json to filesystem paths.
"""

import os
import time
import json
import requests
import shutil
from pathlib import Path

# Default ComfyUI URL (change if needed)
COMFYUI_URL = os.environ.get("COMFYUI_URL", "http://127.0.0.1:8188")
# How long to wait between polls (seconds)
POLL_INTERVAL = 3
# Maximum wait for generation to finish (seconds)
MAX_WAIT_SECONDS = 600

def _upload_image(comfy_url, image_path):
    """Upload image file to ComfyUI. Returns server response JSON if available."""
    print(f"[generator] Uploading image {image_path} to ComfyUI at {comfy_url} ...")
    with open(image_path, "rb") as f:
        files = {"image": (os.path.basename(image_path), f, "image/png")}
        resp = requests.post(f"{comfyui_url.rstrip('/')}/upload/image", files=files)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status": "ok"}

def _send_workflow(comfy_url, workflow_payload):
    """
    Send a workflow (API format JSON) to ComfyUI queue.
    The exact response shape may vary by ComfyUI version; we return the raw response JSON.
    """
    print("[generator] Sending workflow payload to ComfyUI queue ...")
    resp = requests.post(f"{comfy_url.rstrip('/')}/queue", json=workflow_payload, timeout=30)
    resp.raise_for_status()
    try:
        return resp.json()
    except Exception:
        return {"status": "queued"}

def _poll_for_result(comfy_url, queue_info, timeout_seconds=MAX_WAIT_SECONDS):
    """
    Poll the ComfyUI server for results.
    NOTE: ComfyUI endpoint shapes differ across setups. This function uses a conservative
    approach: it waits and attempts to read the /history or /queue status endpoints where possible.
    You may need to adapt it to your ComfyUI deployment (for example, using /queue/{id}).
    Returns whatever 'result' info it can find or None on timeout.
    """
    start = time.time()
    print("[generator] Polling for completion ...")
    while time.time() - start < timeout_seconds:
        try:
            # Try common endpoints; adapt to your ComfyUI if you know the right one.
            # 1) If the queue response gave an id or prompt_id, try /queue/<id>
            qid = queue_info.get("id") or queue_info.get("prompt_id") or queue_info.get("queue_id")
            if qid:
                try:
                    resp = requests.get(f"{comfyui_url.rstrip('/')}/queue/{qid}", timeout=10)
                    if resp.status_code == 200:
                        rj = resp.json()
                        # Heuristics: look for a 'status' or 'complete' marker
                        if rj.get("status") in ("done", "completed", "complete") or rj.get("finished", False):
                            return rj
                except requests.exceptions.HTTPError:
                    pass
                except Exception:
                    pass

            # 2) Fallback: inspect /history (may need auth or not exist)
            try:
                resp = requests.get(f"{comfyui_url.rstrip('/')}/history", timeout=10)
                if resp.status_code == 200:
                    hist = resp.json()
                    # Heuristic: return most recent entry (user should adapt)
                    if isinstance(hist, list) and len(hist) > 0:
                        latest = hist[0]
                        # If latest has outputs or images, assume completion
                        if latest.get("status") in ("done", "completed") or latest.get("outputs"):
                            return latest
            except Exception:
                pass

            # 3) If nothing worked yet, sleep and retry
        except Exception as e:
            print(f"[generator] Poll exception: {e}")
        time.sleep(POLL_INTERVAL)
    print("[generator] Timeout waiting for ComfyUI result.")
    return None

def _save_placeholder_mesh(out_path):
    """Write a small placeholder OBJ so Modly has something to inspect while you adapt the real flow."""
    print(f"[generator] Writing placeholder mesh to {out_path}")
    placeholder = """# Placeholder .obj generated by modly-comfyui-extension
o placeholder
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 0.0 1.0 0.0
f 1 2 3
"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(placeholder)

def generate(inputs, output_dir):
    """
    Entry point called by Modly.
    inputs: dict with keys from manifest (input_image, workflow_json optional)
    output_dir: path where to place the resulting mesh file
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    image_path = inputs.get("input_image")
    workflow_json_path = inputs.get("workflow_json")  # optional path if Modly provides the workflow file

    if not image_path or not os.path.exists(image_path):
        raise FileNotFoundError(f"input_image not found or not provided: {image_path}")

    # 1) Upload image
    try:
        upload_resp = _upload_image(COMFYUI_URL, image_path)
        print("[generator] upload_resp:", upload_resp)
    except Exception as e:
        print(f"[generator] Failed to upload image to ComfyUI: {e}")
        # Continue; some ComfyUI setups automatically pull from a shared folder instead.
    
    # 2) Build or load workflow payload
    if workflow_json_path and os.path.exists(workflow_json_path):
        print(f"[generator] Loading workflow JSON from {workflow_json_path}")
        with open(workflow_json_path, "r", encoding="utf-8") as f:
            workflow_payload = json.load(f)
    else:
        # TODO: Replace this example with the real API-format workflow you exported from ComfyUI.
        # Example minimal placeholder workflow payload. Replace with your nodes & connections.
        workflow_payload = {
            "prompt": {
                "type": "workflow",
                "name": "modly_placeholder_workflow",
                "nodes": {
                    "1": {
                        "class_type": "LoadImage",
                        "inputs": {"image": os.path.basename(image_path)}
                    },
                    "2": {
                        "class_type": "Some3DNode",
                        "inputs": {"image": {"node_id": "1"}}
                    }
                },
                "outputs": {"mesh": {"node_id": "2", "output": "mesh"}}
            }
        }
        print("[generator] No workflow file provided; using internal placeholder payload. Replace with your exported workflow.json for real results.")

    # 3) Send workflow to ComfyUI
    try:
        queue_resp = _send_workflow(COMFYUI_URL, workflow_payload)
        print("[generator] queue_resp:", queue_resp)
    except Exception as e:
        print(f"[generator] Failed to send workflow to ComfyUI: {e}")
        queue_resp = {}

    # 4) Poll for results
    result_info = _poll_for_result(COMFYUI_URL, queue_resp)
    mesh_path = os.path.join(output_dir, "generated_model.obj")

    if result_info:
        # TODO: Adapt this section to your ComfyUI output structure:
        # If ComfyUI returns an output file URL or path, download/copy it here and set mesh_path.
        # Example pseudo-code (adapt to your server):
        #
        # output_url = result_info.get("outputs", {}).get("mesh_file_url")
        # if output_url:
        #     r = requests.get(output_url, stream=True)
        #     with open(mesh_path, "wb") as f:
        #         shutil.copyfileobj(r.raw, f)
        #
        # For now, write a placeholder file so Modly can continue:
        _save_placeholder_mesh(mesh_path)
        print("[generator] Finished: wrote placeholder mesh. Edit generator.py to save real ComfyUI output.")
    else:
        # Timeout / no result — write placeholder so Modly has something to show while you debug
        _save_placeholder_mesh(mesh_path)

    # Return mapping to manifest outputs
    return {"output_mesh": mesh_path}

# If run as script, allow local testing:
if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True, help="Path to test input image")
    ap.add_argument("--out", default="out", help="Output directory")
    ap.add_argument("--workflow", default=None, help="Optional workflow JSON path")
    args = ap.parse_args()
    res = generate({"input_image": args.image, "workflow_json": args.workflow}, args.out)
    print("Result:", res)
